server:
  port: 8080

jwt:
  secret: zluteprasatkoslodolesa585858.

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/etoro
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true

