GET http://localhost:8080/api/v1/assets?sort=DESC&page=0&size=10&search=coca
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b21hcy5zdm9qYW5vdnNreTExQGdtYWlsLmNvbSIsImV4cCI6MTY2NDAyNjAyNiwiaWF0IjoxNjY0MDIyNDI2fQ.t2AnFPqfqp2xPVz3K1ZuQlbsSrjfAQZ7vWTaXYrlfIKK19DLsBU1vH35TJxOZk_CmE2OP7_Ms4igBTcgt5svMQ

